-- CREATED MANUALLY
DROP TABLE IF EXISTS "ItemValue";
DROP TABLE IF EXISTS "Item";
DROP TABLE IF EXISTS "ItemSection";
DROP TABLE IF EXISTS "Migration";
DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "ValueDetail";
DROP TYPE IF EXISTS "ValueType";
